version: "3.2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5050:5001"
    environment:
      SQL_SERVER_NAME: "host.docker.internal"
      SQL_SERVER_PORT: 1434
      SQL_SERVER_INSTANCE_NAME: ""
      SQL_DATABASE_NAME: tdmdev
      SQL_USER_NAME: sa
      SQL_PASSWORD: Dogfood1!
      PORT: 5001
    volumes:
      - ./:/tdm
      - /tdm/node_modules
    command: npx nodemon -w /tdm/server.js -w /tdm/app -w /tdm/middleware -L server.js
